import { Question } from './question.model';

export const QUESTIONS: Question[] = [
  new Question("Question #1",
    "Select the equation of the line represented by the two points, table, or graph.",
    10,
    "https://heyloo-ced60.firebaseapp.com/assets/qanda/1/question1.png",
    ["https://heyloo-ced60.firebaseapp.com/assets/qanda/1/question1answer1.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/1/question1answer2.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/1/question1answer3.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/1/question1answer4.png"],
    0),
  new Question("Question #2",
    "Select the equation of the line represented by the two points, table, or graph.",
    10,
    "https://heyloo-ced60.firebaseapp.com/assets/qanda/2/question2.png",
    ["https://heyloo-ced60.firebaseapp.com/assets/qanda/2/question2answer1.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/2/question2answer2.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/2/question2answer3.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/2/question2answer4.png"],
    1),
  new Question("Question #3",
    "Select the equation of the line represented by the two points, table, or graph.",
    10,
    "https://heyloo-ced60.firebaseapp.com/assets/qanda/3/question3.png",
    ["https://heyloo-ced60.firebaseapp.com/assets/qanda/3/question3answer1.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/3/question3answer2.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/3/question3answer3.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/3/question3answer4.png"],
    2),
    new Question("Question #4",
    "Select the equation of the line represented by the two points, table, or graph.",
    10,
    "https://heyloo-ced60.firebaseapp.com/assets/qanda/4/question4.png",
    ["https://heyloo-ced60.firebaseapp.com/assets/qanda/4/question4answer1.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/4/question4answer2.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/4/question4answer3.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/4/question4answer4.png"],
    3),
new Question("Question #5",
    "Select the equation of the line represented by the two points, table, or graph.",
    10,
    "https://heyloo-ced60.firebaseapp.com/assets/qanda/5/question5.png",
    ["https://heyloo-ced60.firebaseapp.com/assets/qanda/5/question5answer1.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/5/question5answer2.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/5/question5answer3.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/5/question5answer4.png"],
    0),
new Question("Question #6",
    "Select the equation of the line represented by the two points, table, or graph.",
    10,
    "https://heyloo-ced60.firebaseapp.com/assets/qanda/6/question6.png",
    ["https://heyloo-ced60.firebaseapp.com/assets/qanda/6/question6answer1.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/6/question6answer2.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/6/question6answer3.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/6/question6answer4.png"],
    1),
new Question("Question #7",
    "Which graph matches the equation?",
    10,
    "https://heyloo-ced60.firebaseapp.com/assets/qanda/7/question7.png",
    ["https://heyloo-ced60.firebaseapp.com/assets/qanda/7/question7answer1.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/7/question7answer2.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/7/question7answer3.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/7/question7answer4.png"],
    3),
new Question("Question #8",
    "Which graph matches the equation?",
    10,
    "https://heyloo-ced60.firebaseapp.com/assets/qanda/8/question8.png",
    ["https://heyloo-ced60.firebaseapp.com/assets/qanda/8/question8answer1.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/8/question8answer2.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/8/question8answer3.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/8/question8answer4.png"],
    3),
new Question("Question #9",
    "Factor each quadratic expression",
    10,
    "https://heyloo-ced60.firebaseapp.com/assets/qanda/9/question9.png",
    ["https://heyloo-ced60.firebaseapp.com/assets/qanda/9/question9answer1.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/9/question9answer2.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/9/question9answer3.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/9/question9answer4.png"],
    3),
new Question("Question #10",
    "Factor each quadratic expression",
    10,
    "https://heyloo-ced60.firebaseapp.com/assets/qanda/10/question10.png",
    ["https://heyloo-ced60.firebaseapp.com/assets/qanda/10/question10answer1.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/10/question10answer2.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/10/question10answer3.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/10/question10answer4.png"],
    3)
]