import { Question } from './question.model';

export const QUESTIONS: Question[] = [
  new Question("Question #1",
    "Select the equation of the line represented by the two points, table, or graph.",
    10,
    "https://heyloo-ced60.firebaseapp.com/assets/qanda/1/question1.png",
    ["https://heyloo-ced60.firebaseapp.com/assets/qanda/1/question1answer1.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/1/question1answer2.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/1/question1answer3.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/1/question1answer4.png"],
    0),
  new Question("Question #2",
    "Select the equation of the line represented by the two points, table, or graph.",
    10,
    "https://heyloo-ced60.firebaseapp.com/assets/qanda/2/question2.png",
    ["https://heyloo-ced60.firebaseapp.com/assets/qanda/2/question2answer1.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/2/question2answer2.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/2/question2answer3.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/2/question2answer4.png"],
    1),
  new Question("Question #3",
    "Select the equation of the line represented by the two points, table, or graph.",
    10,
    "https://heyloo-ced60.firebaseapp.com/assets/qanda/3/question3.png",
    ["https://heyloo-ced60.firebaseapp.com/assets/qanda/3/question3answer1.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/3/question3answer2.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/3/question3answer3.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/3/question3answer4.png"],
    2),
    new Question("Question #4",
    "Select the equation of the line represented by the two points, table, or graph.",
    10,
    "https://heyloo-ced60.firebaseapp.com/assets/qanda/4/question4.png",
    ["https://heyloo-ced60.firebaseapp.com/assets/qanda/4/question4answer1.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/4/question4answer2.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/4/question4answer3.png",
     "https://heyloo-ced60.firebaseapp.com/assets/qanda/4/question4answer4.png"],
    3)
]